### ISSUE TITLE
I don't know TypeScript

### ISSUE THREAD

**Issue by ismailismail** [alexcorvi/fin-tense#1]
Could someone help to run this project. I have been working on it a while but I couldn't run it.

**Comment by alexcorvi** [comment]
can you elaborate more about the problem you're facing?

**Comment by ismailismail** [comment]
Hi alexcorvi
I created node js project with npm then
in terminal I moved  where I created project
I run npm i --save fin-tense then
I created example.ts file 
I copied your usage example code 
I run "tsc example.ts" in terminal 
Terminal shows that

example.ts:1:22 - error TS2307: Cannot find module 'finnlp'.

1 import * as Fin from "finnlp";
                       ~~~~~~~~


Found 1 error.

**Comment by alexcorvi** [comment]
The repo you're taking the usage example from is like an extension to a library called `finnlp`, so you have to install that too using
```
npm i finnlp
```
also. feel free to check out the documentation: https://finnlp.gitbook.io/fin/

**Comment by ismailismail** [comment]
Thank you alexcorvi

**Comment by alexcorvi** [comment]
You're welcome!
