### ISSUE TITLE
Error when trying to install using npm i --save fin-tense

### ISSUE THREAD

**Issue by arubafna** [alexcorvi/fin-tense#2]
I am trying to run this project, but i am facing some issues.
I am new to this, please consider.

arunima@arunima-VirtualBox:~/Desktop/fin-tense$ npm i --save fin-tense
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "fin-tense"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install fin-tense as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arunima/Desktop/fin-tense/npm-debug.log

**Comment by alexcorvi** [comment]
You're trying to install `fin-tense` inside the package `fin-tense` itself. This package should be a dependency on your project, along with `finnlp` package.

**Comment by arubafna** [comment]
So should i run the command from the directory where i have saved the project folder?
i.e In this the Desktop directory?

**Comment by arubafna** [comment]
Now that the node_modules folder is created, i am trying to run the the example.ts file which contains code from the "usage" section. However i get the following result

arunima@arunima-VirtualBox:~/Desktop/fin-tense$ tsc example.ts
example.ts:6:25 - error TS2339: Property 'tense' does not exist on type 'Run'.

6 const result = instance.tense();
                          ~~~~~


Found 1 error.

**Comment by alexcorvi** [comment]
Start with an empty new directory, name it `my-project` for example, in this directory run the following command:
```
npm i finnlp fin-tense
```
The above command will install both packages: `finnlp` and `fin-tense` in your project, so you can use them as dependencies.
Create a new file `index.js` and copy-paste the example code:
```js
import * as Fin from "finnlp";
import "fin-tense";
// the above two lines will require the dependencies you've just installed
// the lines below will use those dependencies
const sentence = "He was demonstrably wrong."
const instance = new Fin.Run(sentence);
const result = instance.tense();
console.log(result);
```

**Comment by alexcorvi** [comment]
If your node installation does not support `import` you can use this example code:
```js
var Fin = require("finnlp");
require("fin-tense");
// the above two lines will require the dependencies you've just installed
// the lines below will use those dependencies
var sentence = "He was demonstrably wrong.";
var instance = new Fin.Run(sentence);
var result = instance.tense();
console.log(result);
```

**Comment by arubafna** [comment]
Thank you so much! This helped

**Comment by alexcorvi** [comment]
You're welcome

**Comment by arubafna** [comment]
Thank you so much! This helped
